language: go

go:
  - "1.10.x"
# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - mkdir -p release
  - "GOOS=linux  GOARCH=amd64 go build -ldflags \"-X github.com/Dreamlol/promoter/cmd.version=$TRAVIS_TAG\" -o release/promoter-$TRAVIS_TAG-linux-amd64"
#  - "GOOS=linux  GOARCH=arm GOARM=5 go build -ldflags \"-X github.com/Dreamlol/promoter/cmd.version=$TRAVIS_TAG\" -o release/promoter-$TRAVIS_TAG-linux-arm"
#  - "GOOS=darwin GOARCH=amd64 go build -ldflags \"-X github.com/Dreamlol/promoter/cmd.version=$TRAVIS_TAG\" -o release/promoter-$TRAVIS_TAG-darwin-amd64"
#  - "GOOS=windows GOARCH=amd64 go build -ldflags \"-X github.com/Dreamlol/promoter/cmd.version=$TRAVIS_TAG\" -o release/promoter-$TRAVIS_TAG-windows.exe"

# this tells travis-ci to create a github release and deploy artifacts to
# github _only_ when there is a tag associated with a commit. That is what the tags: true means.
# You can setup this section really easily by doing `$ travis setup releases`
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
    - "release/promoter-$TRAVIS_TAG-linux-amd64"
#    - "release/promoter-$TRAVIS_TAG-linux-arm"
#    - "release/promoter-$TRAVIS_TAG-darwin-amd64"
#    - "release/promoter-$TRAVIS_TAG-windows.exe"
  skip_cleanup: true
  on:
    tags: true